insert into ENTIDAD (NO_IDENTIFICACION, VERSION, ID_ENTIDAD) values ('111111', 1, 1);
insert into PERSONA (APELLIDO_PATERNO, APELLIDO_MATERNO, NOMBRES, FECHA_NACIMIENTO, PROFESION, ID_PERSONA) values ('Siles', 'Encinas', 'Ariel', NULL, NULL, 1);
insert into EMPLEADO (FECHA_INGRESO, FECHA_SALIDA, SALARIO, ID_EMPLEADO) values (NULL, NULL, NULL, 1);
insert into USUARIO (USUARIO, CLAVE, EMAIL, FECHA_CREACION, ID_USUARIO) values ('root', '8a8b61dff6b4f92b0cec80be671d61cd23e6391d', NULL, '2008-08-31 22:06:52', 1);

INSERT INTO SECUENCIA (TABLA, VALOR) values ('ENTIDAD', 1);