--Khipus MRP PROD-44: Implementar el reporte del total Acopiado
--Diego H. Loza Fernandez
INSERT  INTO FUNCIONALIDAD (IDFUNCIONALIDAD,CODIGO,DESCRIPCION,PERMISO,NOMBRERECURSO,IDMODULO)
  VALUES (354, 'REPORTCOLLECTEDBYGAB', NULL, 15, 'menu.production.supplierPayments.reports.collectedReportByGAB', 6); 
INSERT  INTO DERECHOACCESO (IDFUNCIONALIDAD,IDROL,PERMISO,IDCOMPANIA,IDMODULO)
  VALUES (354, 50, 15, 1, 6);     
--select * from FUNCIONALIDAD
-- Cambiar el nombre del descuento de OTROS EGRESOSO a OTROS EGRESOS
UPDATE tipomovimientoproductor
SET nombre = 'OTROS DESCUENTOS'
WHERE idtipomovimientoproductor = 5;
-- 
INSERT  INTO FUNCIONALIDAD (IDFUNCIONALIDAD,CODIGO,DESCRIPCION,PERMISO,NOMBRERECURSO,IDMODULO)
  VALUES (355, 'SALARYMOVEMENTDISCOUNTGAB', NULL, 15, 'menu.production.salaryMovementGAB', 6); 
INSERT  INTO DERECHOACCESO (IDFUNCIONALIDAD,IDROL,PERMISO,IDCOMPANIA,IDMODULO)
  VALUES (355, 50, 15, 1, 6);   
  
INSERT  INTO FUNCIONALIDAD (IDFUNCIONALIDAD,CODIGO,DESCRIPCION,PERMISO,NOMBRERECURSO,IDMODULO)
  VALUES (356, 'SALARYMOVEMENTDISCOUNTPRODUCER', NULL, 15, 'menu.production.supplierPayments.rawMaterialProducerDiscountProducer', 6); 
INSERT  INTO DERECHOACCESO (IDFUNCIONALIDAD,IDROL,PERMISO,IDCOMPANIA,IDMODULO)
  VALUES (356, 50, 15, 1, 6);    
--SELECT * FROM  FUNCIONALIDAD  WHERE IDFUNCIONALIDAD = 356
--commit
