--Khipus MRP PROD-34:
--Crear la tabla
/*Create table MOVIMIENTOSALARIOGAB (
	IDMOVIMIENTOSALARIOGAB NUMBER(24,0) NOT NULL ,
	ALCOHOL NUMBER(16,2) default 0.0 ,
	VERSION NUMBER(24,0) NOT NULL ,
	IDCOMPANIA NUMBER(24,0) NOT NULL ,
  IDZONAPRODUCTIVA NUMBER(24,0) NOT NULL ,
  FECHA DATE NOT NULL,
 CONSTRAINT pk_MOVIMIENTOSALARIOGAB primary key (IDMOVIMIENTOSALARIOGAB) 
);
--DROP TABLE MOVIMIENTOSALARIOGAB
ALTER TABLE MOVIMIENTOSALARIOGAB
ADD CONSTRAINT fk_ZONAPRODUCTIVA FOREIGN KEY (IDZONAPRODUCTIVA) REFERENCES ZONAPRODUCTIVA(IDZONAPRODUCTIVA);
*/

Create table TIPOMOVIMIENTOPRODUCTOR (
	IDTIPOMOVIMIENTOPRODUCTOR NUMBER(24,0) NOT NULL ,
	NOMBRE VARCHAR(255) NOT NULL,
	VALOR NUMBER(16,2) DEFAULT 0.0,
	MONEDA VARCHAR(10),
	TIPOMOVIMIENTOGAB VARCHAR(50) NOT NULL,
 CONSTRAINT pk_TIPOMOVIMIENTOPRODUCTOR primary key (IDTIPOMOVIMIENTOPRODUCTOR) 
);
--drop table TIPOMOVIMIENTOPRODUCTOR
Create table TIPOMOVIMIENTOGAB (
	IDTIPOMOVIMIENTOGAB NUMBER(24,0) NOT NULL ,
	NOMBRE VARCHAR(255) NOT NULL,
	VALOR NUMBER(16,2) DEFAULT 0.0,
	MONEDA VARCHAR(10),
	TIPOMOVIMIENTOPRODUCTOR VARCHAR(20),
	TIPOMOVIMIENTOGAB VARCHAR(50) NOT NULL,
  IDCOMPANIA NUMBER(24,0) NOT NULL ,
 CONSTRAINT pk_TIPOMOVIMIENTOGAB primary key (IDTIPOMOVIMIENTOGAB) 
);
-- drop table TIPOMOVIMIENTOGAB
Create table MOVIMIENTOSALARIOPRODUCTOR (
  IDMOVIMIENTOSALARIOPRODUCTOR NUMBER(24,0) NOT NULL ,
	IDPRODUCTORMATERIAPRIMA NUMBER(24,0) NOT NULL ,
	DESCRIPCION varchar(255),
  FECHA DATE NOT NULL,
  IDTIPOMOVIMIENTOPRODUCTOR NUMBER(24,0) NOT NULL ,
  IDCOMPANIA NUMBER(24,0) NOT NULL ,
  CONSTRAINT pk_MOVIMIENTOSALARIOPRODUCTOR primary key (IDMOVIMIENTOSALARIOPRODUCTOR) 
);
ALTER TABLE MOVIMIENTOSALARIOPRODUCTOR
ADD CONSTRAINT fk_PRODUCTORMATERIAPRIMA FOREIGN KEY (IDPRODUCTORMATERIAPRIMA) REFERENCES PRODUCTORMATERIAPRIMA(IDPRODUCTORMATERIAPRIMA);

ALTER TABLE MOVIMIENTOSALARIOPRODUCTOR
ADD CONSTRAINT fk_TIPOMOVIMIENTOPRODUCTOR FOREIGN KEY (IDTIPOMOVIMIENTOPRODUCTOR) REFERENCES TIPOMOVIMIENTOPRODUCTOR(IDTIPOMOVIMIENTOPRODUCTOR);
--commit
-- drop table MOVIMIENTOSALARIOPRODUCTOR 
Create table MOVIMIENTOSALARIOGAB (
  IDMOVIMIENTOSALARIOGAB NUMBER(24,0) NOT NULL ,
	IDZONAPRODUCTIVA NUMBER(24,0) NOT NULL ,
	DESCRIPCION varchar(255),
  FECHA DATE NOT NULL,
	IDTIPOMOVIMIENTOGAB NUMBER(24,0) NOT NULL ,
  IDCOMPANIA NUMBER(24,0) NOT NULL ,
 CONSTRAINT pk_MOVIMIENTOSALARIOGAB primary key (IDMOVIMIENTOSALARIOGAB) 
);
-- DROP TABLE MOVIMIENTOSALARIOGAB
ALTER TABLE MOVIMIENTOSALARIOGAB
ADD CONSTRAINT fk_ZONAPRODUCTIVA FOREIGN KEY (IDZONAPRODUCTIVA) REFERENCES ZONAPRODUCTIVA(IDZONAPRODUCTIVA);

ALTER TABLE MOVIMIENTOSALARIOGAB
ADD CONSTRAINT fk_TIPOMOVIMIENTOGAB FOREIGN KEY (IDTIPOMOVIMIENTOGAB) REFERENCES TIPOMOVIMIENTOGAB(IDTIPOMOVIMIENTOGAB);
--commit

