--SELECT * FROM FUNCIONALIDAD
--Modificar servicios costos reprocesdos
--Diego H. Loza Fernandez
--Fecha de creacion: 08/02/2014
ALTER TABLE PRODUCTOBASE ADD (ESTADO	VARCHAR2(20 BYTE) NULL);
ALTER TABLE PRODUCTOREPROCESADO ADD (UNIDADES NUMBER(6,0) NULL, VOLUMEN NUMBER(8,2) NULL );
--COMMIT