--Khipus MRP PROD-80: Implemtar el reporte RECEPCION DE PEDIDO
--Fecha de creacion: 18/12/2013
--SELECT * FROM FUNCIONALIDAD
--OPCION PEDIDOS
INSERT  INTO FUNCIONALIDAD (IDFUNCIONALIDAD,CODIGO,DESCRIPCION,PERMISO,NOMBRERECURSO,IDMODULO)
  VALUES (359, 'ORDER', NULL, 15, 'menu.customers.order', 1); 
INSERT  INTO DERECHOACCESO (IDFUNCIONALIDAD,IDROL,PERMISO,IDCOMPANIA,IDMODULO)
  VALUES (359, 50, 15, 1, 1);     
--OPCION PEDIDOS REPORTE
INSERT  INTO FUNCIONALIDAD (IDFUNCIONALIDAD,CODIGO,DESCRIPCION,PERMISO,NOMBRERECURSO,IDMODULO)
  VALUES (360, 'ORDERREPORT', NULL, 15, 'menu.customers.order.report', 1); 
INSERT  INTO DERECHOACCESO (IDFUNCIONALIDAD,IDROL,PERMISO,IDCOMPANIA,IDMODULO)
  VALUES (360, 50, 15, 1, 1);     
--OPCION PEDIDOS REPORTE recepcion
INSERT  INTO FUNCIONALIDAD (IDFUNCIONALIDAD,CODIGO,DESCRIPCION,PERMISO,NOMBRERECURSO,IDMODULO)
  VALUES (361, 'ORDERREPORTRECEIPT', NULL, 15, 'menu.customers.order.report.receipt', 1); 
INSERT  INTO DERECHOACCESO (IDFUNCIONALIDAD,IDROL,PERMISO,IDCOMPANIA,IDMODULO)
  VALUES (361, 50, 15, 1, 1);     
--commit
alter table WISE.inv_articulos ADD (NOMBRECORTO VARCHAR(100) NULL);