--Khipus MRP PROD-69: Arreglar el control de los insumos que no deben ser tomados en cuenta.
--Diego H. Loza Fernandez
--Fecha de creacion: 12/11/2013
Create table ESTADOARTICULO (
	IDESTADOARTICULO NUMBER(24,0) NOT NULL ,
  COD_ART	VARCHAR2(6 BYTE) NOT NULL,
  NO_CIA	VARCHAR2(2 BYTE) NOT NULL,
  ESTADO VARCHAR2(255) NULL,
  DESCRIPCION VARCHAR2(255) NULL,
  IDCOMPANIA NUMBER(24,0) NOT NULL ,
 CONSTRAINT pk_ESTADOARTICULO primary key (IDESTADOARTICULO) 
);

ALTER TABLE ESTADOARTICULO
ADD CONSTRAINT fk_INV_ARTICULOS_ESTADO FOREIGN KEY (NO_CIA,COD_ART) REFERENCES WISE.INV_ARTICULOS(NO_CIA,COD_ART);
--COMMIT
