--Khipus MRP PROD-90
--Fecha de creacion: 13/05/2014
--descripcion : 
INSERT  INTO FUNCIONALIDAD (IDFUNCIONALIDAD,CODIGO,DESCRIPCION,PERMISO,NOMBRERECURSO,IDMODULO)
  VALUES (386, 'ESTIMATIONSTOCKREPORT', NULL, 15,'Reports.warehouse.EstimationStockReport', 1); 
INSERT  INTO DERECHOACCESO (IDFUNCIONALIDAD,IDROL,PERMISO,IDCOMPANIA,IDMODULO)
  VALUES (386, 50, 15, 1, 1);   
--select * from funcionalidad  
--select * from modulo;
--COMMIT