--Khipus MRP PROD-69: Arreglar el control de los insumos que no deben ser tomados en cuenta.
--Diego H. Loza Fernandez
--Fecha de creacion: 12/11/2013
Create table ESTADOARTICULO (
	IDESTADOARTICULO NUMBER(24,0) NOT NULL ,
  COD_ART	VARCHAR2(6 BYTE) NOT NULL,
  NO_CIA	VARCHAR2(2 BYTE) NOT NULL,
  ESTADO VARCHAR2(255) NULL,
  DESCRIPCION VARCHAR2(255) NULL,
  IDCOMPANIA NUMBER(24,0) NOT NULL ,
 CONSTRAINT pk_ESTADOARTICULO primary key (IDESTADOARTICULO) 
);
-- DROP TABLE ESTADOARTICULO;
ALTER TABLE ESTADOARTICULO
ADD CONSTRAINT fk_INV_ARTICULOS_ESTADO FOREIGN KEY (NO_CIA,COD_ART) REFERENCES WISE.INV_ARTICULOS(NO_CIA,COD_ART);
--
INSERT  INTO ESTADOARTICULO (IDESTADOARTICULO,COD_ART,NO_CIA,ESTADO,DESCRIPCION,IDCOMPANIA)
  VALUES (1,'100','01','NOVERIFICABLE','ESTE ARTICULO NO DEBE SER BERIFICADO',1); 
delete estadoarticulo;  
--COMMIT
