--Khipus MRP PROD-69: Arreglar el control de los insumos que no deben ser tomados en cuenta.
--Diego H. Loza Fernandez
--Fecha de creacion: 12/11/2013

CREATE TABLE ORDENINSUMO 
  (	
    IDORDENINSUMO NUMBER(24,0) NOT NULL ,     
    CANTIDAD NUMBER(24,2) NOT NULL , 
    IDORDENPRODUCCION NUMBER(24,0) NOT NULL ,         
    COD_ART	VARCHAR2(6 BYTE) NOT NULL,
    NO_CIA	VARCHAR2(2 BYTE) NOT NULL,    
    CANTIDADSTOCK NUMBER(24,2) NOT NULL , 
    CONSTRAINT pk_ORDENINSUMO primary key (IDORDENINSUMO)
  );
--drop table ORDENINSUMO  
--
ALTER TABLE ORDENINSUMO
ADD CONSTRAINT fk_INV_ARTICULOS_INSUMO FOREIGN KEY (NO_CIA,COD_ART) REFERENCES WISE.INV_ARTICULOS(NO_CIA,COD_ART);
ALTER TABLE ORDENINSUMO
ADD CONSTRAINT fk_ORDENPRODUCCION_INSUMO FOREIGN KEY (IDORDENPRODUCCION) REFERENCES ORDENPRODUCCION(IDORDENPRODUCCION);
--commit