/* Ariel:01112013 - EMPLOYEE TIME CARD */
CREATE TABLE EOS.TARJETATIEMPOEMPLEADO
(
  IDTARJETATIEMPOEMPLEADO       NUMBER(24)                   NOT NULL,
  HORAINICIO                    DATE                         NOT NULL,
  HORAFIN                       DATE                         NOT NULL,
  DESCRIPCION                   CLOB,
  IDEMPLEADO                    NUMBER(24)                   NOT NULL,
  IDPLANIFICACIONPROD           NUMBER(24)                   NULL,
  IDCOMPANIA                    NUMBER(24)                   NOT NULL
);

ALTER TABLE EOS.TARJETATIEMPOEMPLEADO ADD CONSTRAINT PK_TARJETATIEMPOEMP PRIMARY KEY (IDTARJETATIEMPOEMPLEADO);

ALTER TABLE EOS.TARJETATIEMPOEMPLEADO ADD CONSTRAINT FK1029TARJETATIEMPOEMP FOREIGN KEY (IDCOMPANIA) REFERENCES EOS.COMPANIA (IDCOMPANIA);

ALTER TABLE EOS.TARJETATIEMPOEMPLEADO ADD CONSTRAINT FK1030TARJETATIEMPOEMP FOREIGN KEY (IDEMPLEADO) REFERENCES EOS.EMPLEADO (IDEMPLEADO);

insert into FUNCIONALIDAD (IDFUNCIONALIDAD,CODIGO,PERMISO,NOMBRERECURSO,IDMODULO) values ((select max(idfuncionalidad+1) from funcionalidad),'EMPLOYEETIMECARD','15','menu.production.employeeTimeCard','6');
