--Khipus MRP PROD-34:
--Crear la tabla
Create table MOVIMIENTOSALARIOPRODUCTOR (
	IDMOVIMIENTOSALARIOPRODUCTOR NUMBER(24,0) NOT NULL ,
	YOGURT NUMBER(16,2) default 0.0 ,
	VETERINARIO NUMBER(16,2) default 0.0 ,
	CREDITO NUMBER(16,2) default 0.0 ,
	TACHOS NUMBER(16,2) default 0.0 ,
	RETENCION NUMBER(16,2) default 0.0 ,
	OTROSINGRESOS NUMBER(16,2) default 0.0 ,
	OTROSDESCUENTOS NUMBER(16,2) default 0.0 ,
	VERSION NUMBER(24,0) NOT NULL ,
	IDCOMPANIA NUMBER(24,0) NOT NULL ,
  IDPRODUCTORMATERIAPRIMA NUMBER(24,0) NOT NULL ,
 CONSTRAINT pk_MOVIMIENTOSALARIOPRODUCTOR primary key (IDMOVIMIENTOSALARIOPRODUCTOR) 
);
--DROP TABLE MOVIMIENTOSALARIOPRODUCTOR
ALTER TABLE MOVIMIENTOSALARIOPRODUCTOR
ADD CONSTRAINT fk_PRODUCTORMATERIAPRIMA FOREIGN KEY (IDPRODUCTORMATERIAPRIMA) REFERENCES PRODUCTORMATERIAPRIMA(IDPRODUCTORMATERIAPRIMA);

Create table MOVIMIENTOSALARIOGAB (
	IDMOVIMIENTOSALARIOGAB NUMBER(24,0) NOT NULL ,
	ALCOHOL NUMBER(16,2) default 0.0 ,
	VERSION NUMBER(24,0) NOT NULL ,
	IDCOMPANIA NUMBER(24,0) NOT NULL ,
  IDZONAPRODUCTIVA NUMBER(24,0) NOT NULL ,
 CONSTRAINT pk_MOVIMIENTOSALARIOGAB primary key (IDMOVIMIENTOSALARIOGAB) 
);
--DROP TABLE MOVIMIENTOSALARIOPRODUCTOR
ALTER TABLE MOVIMIENTOSALARIOGAB
ADD CONSTRAINT fk_PRODUCTORMATERIAPRIMA FOREIGN KEY (IDZONAPRODUCTIVA) REFERENCES PRODUCTORMATERIAPRIMA(IDZONAPRODUCTIVA);
select * from MOVIMIENTOSALARIOGAB