/* 08102013 Ariel: Modify the data type, column PESOCONTENEDOR in COMPOSICIONPRODUCTO */
ALTER TABLE COMPOSICIONPRODUCTO ADD AUX NUMBER(16,2) NULL;
UPDATE COMPOSICIONPRODUCTO SET AUX = PESOCONTENEDOR;
ALTER TABLE COMPOSICIONPRODUCTO MODIFY PESOCONTENEDOR NULL;
UPDATE COMPOSICIONPRODUCTO SET PESOCONTENEDOR = NULL;
ALTER TABLE COMPOSICIONPRODUCTO MODIFY PESOCONTENEDOR NUMBER(16,2);
UPDATE COMPOSICIONPRODUCTO SET PESOCONTENEDOR = AUX;
ALTER TABLE COMPOSICIONPRODUCTO MODIFY PESOCONTENEDOR NOT NULL;
ALTER TABLE COMPOSICIONPRODUCTO DROP COLUMN AUX;

/* 08102013 Ariel: Modify the data type, column PESOCONTENEDOR in ORDENPRODUCCION */
ALTER TABLE ORDENPRODUCCION ADD AUX NUMBER(16,2) NULL;
UPDATE ORDENPRODUCCION SET AUX = PESOCONTENEDOR;
ALTER TABLE ORDENPRODUCCION MODIFY PESOCONTENEDOR NULL;
UPDATE ORDENPRODUCCION SET PESOCONTENEDOR = NULL;
ALTER TABLE ORDENPRODUCCION MODIFY PESOCONTENEDOR NUMBER(16,2);
UPDATE ORDENPRODUCCION SET PESOCONTENEDOR = AUX;
ALTER TABLE ORDENPRODUCCION MODIFY PESOCONTENEDOR NOT NULL;
ALTER TABLE ORDENPRODUCCION DROP COLUMN AUX;


--
DELETE FROM INGREDIENTEPRODUCCION;
DELETE FROM COMPOSICIONPRODUCTO;

DELETE FROM SECUENCIA WHERE TABLA LIKE 'INGREDIENTEPRODUCCION';
DELETE FROM SECUENCIA WHERE TABLA LIKE 'COMPOSICIONPRODUCTO';