--Khipus KHIPUS-29
--Sacar el total de leche por grupo de articulo
--Diego H. Loza Fernandez
--Fecha de creacion: 19/02/2014
ALTER TABLE PLANIFICACIONPRODUCCION ADD (TOTALLECHEQUESO	NUMBER(9) NULL);
ALTER TABLE PLANIFICACIONPRODUCCION ADD (TOTALLECHEUHT	NUMBER(9) NULL);
ALTER TABLE PLANIFICACIONPRODUCCION ADD (TOTALLECHEYOGURT	NUMBER(9) NULL);
ALTER TABLE PLANIFICACIONPRODUCCION ADD (TOTALLECHEREPROCESO	NUMBER(9) NULL);
--COMMIT
--permiso para porcentaje graso 
INSERT  INTO FUNCIONALIDAD (IDFUNCIONALIDAD,CODIGO,DESCRIPCION,PERMISO,NOMBRERECURSO,IDMODULO)
  VALUES (366, 'SINGLESAVEGRAASEPERCENTAGE', NULL, 15, 'BaseProduct.percentajeGrease', 6); 
INSERT  INTO DERECHOACCESO (IDFUNCIONALIDAD,IDROL,PERMISO,IDCOMPANIA,IDMODULO)
  VALUES (366, 50, 15, 1, 6);     
--select * from funcionalidad;  
--select * from modulo
--rollback
--Khipus KHIPUS-26
--Implementar la cantidad de leche total usada en una orden de produccion
--Diego H. Loza Fernandez
--Fecha de creacion: 14/02/2014
ALTER TABLE PLANIFICACIONPRODUCCION ADD (TOTALLECHEPRODUCIDA	NUMBER(9) NULL);
--COMMIT