--Khipus MRP PROD-84: Imlementar el registro de porcentaje graso
--Diego H. Loza Fernandez
--Fecha de creacion: 27/01/2014
ALTER TABLE PLANILLAACOPIO ADD PORCENTAJEGRASA NUMBER(16,2) default 0.0 NULL;
ALTER TABLE ORDENPRODUCCION ADD PORCENTAJEGRASA NUMBER(16,2) default 0.0 NULL;
--commit
--OPCION resumen kardex
INSERT  INTO FUNCIONALIDAD (IDFUNCIONALIDAD,CODIGO,DESCRIPCION,PERMISO,NOMBRERECURSO,IDMODULO)
  VALUES (363, 'KARDEXSUMMARYREPORT', NULL, 15, 'Reports.kardex.summary.menu.title', 1); 
INSERT  INTO DERECHOACCESO (IDFUNCIONALIDAD,IDROL,PERMISO,IDCOMPANIA,IDMODULO)
  VALUES (363, 50, 15, 1, 9);     
--OPCION registro de porcentaje graso
INSERT  INTO FUNCIONALIDAD (IDFUNCIONALIDAD,CODIGO,DESCRIPCION,PERMISO,NOMBRERECURSO,IDMODULO)
  VALUES (364, 'SAVEGRAASEPERCENTAGE', NULL, 15, 'ProductionOrder.percentajeGrease', 6); 
INSERT  INTO DERECHOACCESO (IDFUNCIONALIDAD,IDROL,PERMISO,IDCOMPANIA,IDMODULO)
  VALUES (364, 50, 15, 1, 6);     
--Khipus MRP PROD-83: Implementar el re procesado de productos
--Diego H. Loza Fernandez
--Fecha de creacion: 29/01/2014
/*ALTER TABLE ORDENPRODUCCION drop column IDMETAPRODUCTOPRODUCCION NUMBER(24,0) NULL;
alter table ORDENPRODUCCION drop constraint FK_ORDENPRODUCCION_METAPROD
ALTER TABLE ORDENPRODUCCION ADD CONSTRAINT FK_ORDENPRODUCCION_METAPROD 
FOREIGN KEY (IDMETAPRODUCTOPRODUCCION) REFERENCES METAPRODUCTOPRODUCCION (IDMETAPRODUCTOPRODUCCION);
*/
--commit