/* PROD-22 Ariel: Add column for state control. */
ALTER TABLE EOS.PLANILLAACOPIO ADD ESTADO VARCHAR2(3) NULL;
UPDATE EOS.PLANILLAACOPIO SET ESTADO = 'PEN' WHERE ESTADO IS NULL;
COMMIT;

/* PROD-22 Ariel: Add column CTATRANSALM1MN "MATERIA PRIMA PARA PRODUCCION". */
DELETE FROM WISE.CONFIGURACION;
ALTER TABLE WISE.CONFIGURACION ADD CTATRANSALM1MN VARCHAR2(20) NOT NULL; /* "insufficient privileges" to EOS schema */
INSERT INTO WISE.CONFIGURACION (NO_CIA,CTADIFTIPCAM,VERSION,CTAANTPROVME,CTAANTPROVMN,CTAALMME,CTAALMMN,CTAAITB,CTAPROVOBU,NO_USR_TESO,NO_USR_CONTA,NO_USR_SIS,PAGOCTABCOMN,PAGOCTABCOME,IDCARGODOC,CTAIVACREFIMN,CTAIVACREFIME,CTAAFET,IDDEFTIPODOC,IDDEFSALMUJ,IDDEFSALHOM,URLREDIREVALPROG,URLREDIREVALPROGEST,URLREDIREVALPROGDOC,URLREDIREVALPROGAE,URLREDIREVALPROGJC,OCCODIFACTIVA,ACTIVOAUTDOC_TESO,ACTIVOAUTDOC_CXP,IDCOMPANIA,RETENCIONPRESTAMOANTI,AUTOMODIFCONTRATO,HABILITAR_VENTA_ART,CTAIVACREFITRMN,CTATRANSALMME,CTATRANSALMMN,CODMODIFCONTRATO,AGUI_BASICO,TIPO_DOC_CAJA,HRSDIALABORAL,NO_USR_RPAGOS,ANIO_GEN_RPAGOS,IDCATEGORIAPUESTODLH,IDCATEGORIAPUESTODTH,IDTIPOSUELDODLH,IDTIPOSUELDODTH,COD_CC,NO_USR_PAGAR,CTADEPTRAMN,CTADEPTRAME,NO_USR_CONTARRHH, CTATRANSALM1MN) values ('01','40201001002001','6','10103003006001','10103003006001','10601003001004','10601003001004','5','4','ADM','ACC','ADM','1234','1234','1','10202001002001','10202001002001','1','101','31','30','HTTP://PORTAL.UDABOL.EDU.BO','HTTP://PORTAL.UDABOL.EDU.BO:7777/PLS/PORTAL/URL/PAGE/ISKAY_ESTUDIANTE/WSISS_EST_INICIO/WSISS_EVALUACION_EST','HTTP://PORTAL.UDABOL.EDU.BO:7777/PLS/PORTAL/URL/PAGE/ISKAY_AUTORIDAD/WSISS_AUTORIDADES_INICIO/WSISS_EVALUACION_DOC','HTTP://PORTAL.UDABOL.EDU.BO:7777/PLS/PORTAL/URL/PAGE/ISKAY_AUTORIDAD/WSISS_AUTORIDADES_INICIO/WSISS_EVALUACION_DOC','HTTP://PORTAL.UDABOL.EDU.BO:7777/PLS/PORTAL/URL/PAGE/ISKAY_AUTORIDAD/WSISS_AUTORIDADES_INICIO/WSISS_EVALUACION_DOC','1','SI','SI','1','0','0','SI','1','10201001001004','10601003001006','1','0','PE','8','ACC','2013','1','1','1','1','0101','ADM','2','2','ADM', '10601003001007');
COMMIT;

/* PROD-22 Ariel: Inserting for payroll approval collection */
insert into FUNCIONALIDAD (IDFUNCIONALIDAD,CODIGO,PERMISO,NOMBRERECURSO,IDMODULO) values ((select max(idfuncionalidad+1) from funcionalidad),'COLLECTIONFORMAPPROVAL','1','menu.production.collectionForm.approval','6');
COMMIT;