
--Khipus MRP PROD-45: Generacion de asientos contables por quincena
--Diego H. Loza Fernandez
--Fecha de creacion: 19/10/2013
INSERT  INTO FUNCIONALIDAD (IDFUNCIONALIDAD,CODIGO,DESCRIPCION,PERMISO,NOMBRERECURSO,IDMODULO)
  VALUES (357, 'PRODUCTDISTRIBUTIONREPORT', NULL, 15, 'ProductionPlanning.generateDocumnt', 6); 
INSERT  INTO DERECHOACCESO (IDFUNCIONALIDAD,IDROL,PERMISO,IDCOMPANIA,IDMODULO)
  VALUES (357, 50, 15, 1, 6);     
--SELECT * FROM FUNCIONALIDAD
--Khipus PROD-61: Implementar las señales de advertencia en el calculo de la cantidad deseada
--Diego H. Loza Fernandez
--Fecha de creacion: 25/10/2013
alter table INGREDIENTEPRODUCCION add (INGREDIENTEVERIFICABLE VARCHAR(15) null);
update INGREDIENTEPRODUCCION set ingredienteverificable = 'VERIFICABLE';
update INGREDIENTEPRODUCCION set ingredienteverificable = 'NOVERIFICABLE' where idmetaproductoproduccion = 90;
--Khipus MRP PROD-65: Implementar el manejo de materiales de produccion
--Diego H. Loza Fernandez
--Fecha de creacion: 31/10/2013
Create table ORDENMATERIAL (
	IDORDENMATERIAL NUMBER(24,0) NOT NULL ,
  COD_ART	VARCHAR2(6 BYTE) NOT NULL,
  NO_CIA	VARCHAR2(2 BYTE) NOT NULL,
  IDORDENPRODUCCION	NUMBER(24,0) NULL,  
  CANTIDADPESOSOLICITADA NUMBER(16,2) NULL,
  CANTIDADUNIDADSOLICITADA NUMBER(16,2) NULL,
  CANTIDADPESOUSADA NUMBER(16,2) NULL,
  CANTIDADPESORETORNADA NUMBER(16,2) NULL,  
  PRECIOTOTAL NUMBER(16,2) NULL,  
  IDCOMPANIA NUMBER(24,0) NOT NULL ,
 CONSTRAINT pk_ORDENMATERIAL primary key (IDORDENMATERIAL) 
);
--drop table ORDENMATERIAL
--select * from ORDENMATERIAL
ALTER TABLE ORDENMATERIAL
ADD CONSTRAINT fk_INV_ARTICULOS FOREIGN KEY (NO_CIA,COD_ART) REFERENCES WISE.INV_ARTICULOS(NO_CIA,COD_ART);
ALTER TABLE ORDENMATERIAL
ADD CONSTRAINT fk_ORDENPRODUCCION FOREIGN KEY (IDORDENPRODUCCION) REFERENCES ORDENPRODUCCION(IDORDENPRODUCCION);
--COMMIT
ALTER TABLE ORDENPRODUCCION add (PRECIOTOTALMATERIAL NUMBER(16,2) NULL);
ALTER TABLE ORDENPRODUCCION add (PRECIOTOTALINSUMO NUMBER(16,2) NULL);
ALTER TABLE ORDENPRODUCCION add (PRECIOTOTALMANOOBRA NUMBER(16,2) NULL);
ALTER TABLE ORDENPRODUCCION add (COSTOTOALPRODUCCION NUMBER(16,2) NULL);
--COMMIT
ALTER TABLE VALEINSUMOSREQUERIDOS add (PRECIOCOSTOTOTAL NUMBER(16,2) NULL);
/* Ariel:01112013 - EMPLOYEE TIME CARD */
CREATE TABLE EOS.TARJETATIEMPOEMPLEADO
(
  IDTARJETATIEMPOEMPLEADO       NUMBER(24)                   NOT NULL,
  HORAINICIO                    DATE                         NOT NULL,
  HORAFIN                       DATE                         NOT NULL,
  DESCRIPCION                   CLOB,
  IDEMPLEADO                    NUMBER(24)                   NOT NULL,
  IDORDENPRODUCCION             NUMBER(24)                   NULL,
  IDTIPOTAREAPROD               NUMBER(24)                   NOT NULL,
  IDCOMPANIA                    NUMBER(24)                   NOT NULL
);

ALTER TABLE EOS.TARJETATIEMPOEMPLEADO ADD CONSTRAINT PK_TARJETATIEMPOEMP PRIMARY KEY (IDTARJETATIEMPOEMPLEADO);
ALTER TABLE EOS.TARJETATIEMPOEMPLEADO ADD CONSTRAINT FK1029TARJETATIEMPOEMP FOREIGN KEY (IDCOMPANIA) REFERENCES EOS.COMPANIA (IDCOMPANIA);
ALTER TABLE EOS.TARJETATIEMPOEMPLEADO ADD CONSTRAINT FK1030TARJETATIEMPOEMP FOREIGN KEY (IDEMPLEADO) REFERENCES EOS.EMPLEADO (IDEMPLEADO);
ALTER TABLE EOS.TARJETATIEMPOEMPLEADO ADD CONSTRAINT FK_ORDENPRODUCCION_TARJETATIEM FOREIGN KEY (IDORDENPRODUCCION) REFERENCES EOS.ORDENPRODUCCION (IDORDENPRODUCCION);

insert into FUNCIONALIDAD (IDFUNCIONALIDAD,CODIGO,PERMISO,NOMBRERECURSO,IDMODULO) values ((select max(idfuncionalidad+1) from funcionalidad),'EMPLOYEETIMECARD','15','menu.production.employeeTimeCard','6');

--
CREATE TABLE EOS.TIPOTAREAPROD
(
    IDTIPOTAREAPROD NUMBER(24)                    NOT NULL,
    NOMBRE          VARCHAR2(100 CHAR)            NOT NULL,
    VERSION         NUMBER(24)                    NOT NULL,
    IDCOMPANIA      NUMBER(24)                    NOT NULL
);

ALTER TABLE EOS.TIPOTAREAPROD ADD CONSTRAINT PK_TIPOTAREAPROD PRIMARY KEY (IDTIPOTAREAPROD);
ALTER TABLE EOS.TARJETATIEMPOEMPLEADO ADD CONSTRAINT FK_TIPOTAREAPROD_TARJETATIEM FOREIGN KEY (IDTIPOTAREAPROD) REFERENCES EOS.TIPOTAREAPROD (IDTIPOTAREAPROD);

