
--Khipus MRP PROD-74: Modificar el registro de horas de la mano de obra
--Diego H. Loza Fernandez
--Fecha de creacion: 26/11/2013

ALTER TABLE TIPOTAREAPROD ADD (NO_CIA	VARCHAR2(2 BYTE) NOT NULL);
ALTER TABLE TIPOTAREAPROD ADD (COD_GRU	VARCHAR2(3 BYTE) NOT NULL);

ALTER TABLE TIPOTAREAPROD
ADD CONSTRAINT fk_INV_GRUPOS_TIPOTAREAPROD FOREIGN KEY (NO_CIA,COD_GRU) REFERENCES WISE.INV_GRUPOS(NO_CIA,COD_GRU);

Insert into EOS.TIPOTAREAPROD (IDTIPOTAREAPROD,NOMBRE,VERSION,IDCOMPANIA,no_cia,cod_gru) values ('2','PREPARADO','0','1','01','6');
Insert into EOS.TIPOTAREAPROD (IDTIPOTAREAPROD,NOMBRE,VERSION,IDCOMPANIA,no_cia,cod_gru) values ('4','ENVASADO','0','1','01','6');
Insert into EOS.TIPOTAREAPROD (IDTIPOTAREAPROD,NOMBRE,VERSION,IDCOMPANIA,no_cia,cod_gru) values ('5','ETIQUETADO','0','1','01','6');
Insert into EOS.TIPOTAREAPROD (IDTIPOTAREAPROD,NOMBRE,VERSION,IDCOMPANIA,no_cia,cod_gru) values ('6','CONTROL PRODUCTO TERMINADO','0','1','01','6');
Insert into EOS.TIPOTAREAPROD (IDTIPOTAREAPROD,NOMBRE,VERSION,IDCOMPANIA,no_cia,cod_gru) values ('7','SUPERVISION','0','1','01','6');
Insert into EOS.TIPOTAREAPROD (IDTIPOTAREAPROD,NOMBRE,VERSION,IDCOMPANIA,no_cia,cod_gru) values ('10','OTROS','0','1','01','6');
Insert into EOS.TIPOTAREAPROD (IDTIPOTAREAPROD,NOMBRE,VERSION,IDCOMPANIA,no_cia,cod_gru) values ('3','ESTERILIZADO','0','1','01','6');
Insert into EOS.TIPOTAREAPROD (IDTIPOTAREAPROD,NOMBRE,VERSION,IDCOMPANIA,no_cia,cod_gru) values ('1','PREPARADO EQUIPOS','0','1','01','6');
Insert into EOS.TIPOTAREAPROD (IDTIPOTAREAPROD,NOMBRE,VERSION,IDCOMPANIA,no_cia,cod_gru) values ('8','LIMPIEZA EQUIPO','0','1','01','6');
Insert into EOS.TIPOTAREAPROD (IDTIPOTAREAPROD,NOMBRE,VERSION,IDCOMPANIA,no_cia,cod_gru) values ('9','LIMPIEZA GENERAL','0','1','01','6');
---commit
CREATE TABLE CONFIGRUPO (
   IDCONFIGRUPO NUMBER (24,0) NOT NULL
  ,TIPO VARCHAR(255) NULL
  ,NO_CIA	VARCHAR2(2 BYTE) NOT NULL
  ,COD_GRU	VARCHAR2(3 BYTE) NOT NULL
  ,VERSION   NUMBER(24) NOT NULL
  ,IDCOMPANIA NUMBER(24) NOT NULL
  ,CONSTRAINT pk_CONFIGRUPO PRIMARY KEY (IDCONFIGRUPO)
);
--drop table CONFIGRUPO
ALTER TABLE CONFIGRUPO
ADD CONSTRAINT fk_INV_GRUPOS_CONFIGRUPO FOREIGN KEY (NO_CIA,COD_GRU) REFERENCES WISE.INV_GRUPOS(NO_CIA,COD_GRU);

INSERT INTO CONFIGRUPO ( IDCONFIGRUPO,TIPO,NO_CIA,COD_GRU,VERSION,IDCOMPANIA) VALUES (1,'AREA_PRODUCTOS','01','6',0,1);
--commit

ALTER TABLE TARJETATIEMPOEMPLEADO ADD (NO_CIA	VARCHAR2(2 BYTE) NOT NULL);
ALTER TABLE TARJETATIEMPOEMPLEADO ADD (COD_SUB	VARCHAR2(3 BYTE) NOT NULL);
ALTER TABLE TARJETATIEMPOEMPLEADO ADD (COD_GRU	VARCHAR2(3 BYTE) NOT NULL);

ALTER TABLE TARJETATIEMPOEMPLEADO
ADD CONSTRAINT fk_INV_SUBGRUPOS_TARJETA FOREIGN KEY (NO_CIA,COD_GRU,COD_SUB) REFERENCES WISE.INV_SUBGRUPOS(NO_CIA,COD_GRU,COD_SUB);
--hacer el HORAFIN nullable
--COMMIT
--