--Khipus KHIPUS-29
--Sacar el total de leche por grupo de articulo
--Diego H. Loza Fernandez
--Fecha de creacion: 19/02/2014
ALTER TABLE PLANIFICACIONPRODUCCION ADD (TOTALLECHEQUESO	NUMBER(9) NULL);
ALTER TABLE PLANIFICACIONPRODUCCION ADD (TOTALLECHEUHT	NUMBER(9) NULL);
ALTER TABLE PLANIFICACIONPRODUCCION ADD (TOTALLECHEYOGURT	NUMBER(9) NULL);
ALTER TABLE PLANIFICACIONPRODUCCION ADD (TOTALLECHEREPROCESO	NUMBER(9) NULL);
--COMMIT