--Khipus MRP PROD-60: Hacer que la leche cruda sea parametrizable.
--Diego H. Loza Fernandez
--Fecha de creacion: 19/11/2013
Insert into ESTADOARTICULO (IDESTADOARTICULO,COD_ART,NO_CIA,ESTADO,DESCRIPCION,IDCOMPANIA) 
values ('2','26','01','PARAMETRIZABLE','ESTE ARTICULO ES PARAMETRIZABLE','1');  

ALTER TABLE ORDENINSUMO ADD (FORMULAMATEMATICA	VARCHAR2(500 BYTE));
--commit;