--Khipus KHIPUS-84
--Fecha de creacion: 10/06/2014
--descripcion : Implementar el reporte de leche cruda
--Permiso: Reportes de produccion diaria
INSERT  INTO FUNCIONALIDAD (IDFUNCIONALIDAD,CODIGO,DESCRIPCION,PERMISO,NOMBRERECURSO,IDMODULO)
  VALUES (393, 'REPORTPRODUCCTIONDAILY', NULL, 15,'menu.production.planification.ReportesPermisos', 6); 
INSERT  INTO DERECHOACCESO (IDFUNCIONALIDAD,IDROL,PERMISO,IDCOMPANIA,IDMODULO)
  VALUES (393, 50, 15, 1, 6);   
--Permiso: Reporte de leche cruda
INSERT  INTO FUNCIONALIDAD (IDFUNCIONALIDAD,CODIGO,DESCRIPCION,PERMISO,NOMBRERECURSO,IDMODULO)
  VALUES (394, 'REPORTMILKRAW', NULL, 15,'menu.production.planification.ReportMilkRaw', 6); 
INSERT  INTO DERECHOACCESO (IDFUNCIONALIDAD,IDROL,PERMISO,IDCOMPANIA,IDMODULO)
  VALUES (394, 50, 15, 1, 6);   
--Permisos: Reporte de articulos producidos del mes 
INSERT  INTO FUNCIONALIDAD (IDFUNCIONALIDAD,CODIGO,DESCRIPCION,PERMISO,NOMBRERECURSO,IDMODULO)
  VALUES (395, 'REPORTPRODUCTPRODUCED', NULL, 15,'menu.production.planification.produced', 6); 
INSERT  INTO DERECHOACCESO (IDFUNCIONALIDAD,IDROL,PERMISO,IDCOMPANIA,IDMODULO)
  VALUES (395, 50, 15, 1, 6);     
--select * from funcionalidad;  
--select * from modulo;
--ALTER TABLE WISE.COM_ENCOC ADD (CONFACTURA	VARCHAR(50) NULL);
--COMMIT