--Diego H. Loza Fernandez
--arreglando los permisos de produccion

INSERT  INTO FUNCIONALIDAD (IDFUNCIONALIDAD,CODIGO,DESCRIPCION,PERMISO,NOMBRERECURSO,IDMODULO)
  VALUES (410, 'PRODUCTCOMPOSITION', NULL, 15, 'menu.production.planification.productFormulation', 6); 
INSERT  INTO DERECHOACCESO (IDFUNCIONALIDAD,IDROL,PERMISO,IDCOMPANIA,IDMODULO)
  VALUES (410, 50, 15, 1, 6);     
  
INSERT  INTO FUNCIONALIDAD (IDFUNCIONALIDAD,CODIGO,DESCRIPCION,PERMISO,NOMBRERECURSO,IDMODULO)
  VALUES (411, 'PRODUCTDISTRIBUTION', NULL, 15, 'menu.production.planification.distribution', 6); 
INSERT  INTO DERECHOACCESO (IDFUNCIONALIDAD,IDROL,PERMISO,IDCOMPANIA,IDMODULO)
  VALUES (411, 50, 15, 1, 6);    
  
INSERT  INTO FUNCIONALIDAD (IDFUNCIONALIDAD,CODIGO,DESCRIPCION,PERMISO,NOMBRERECURSO,IDMODULO)
  VALUES (412, 'REPORTMILKRAW', NULL, 15, 'menu.production.planification.ReportMilkRaw', 6); 
INSERT  INTO DERECHOACCESO (IDFUNCIONALIDAD,IDROL,PERMISO,IDCOMPANIA,IDMODULO)
  VALUES (412, 50, 15, 1, 6);      
  
INSERT  INTO FUNCIONALIDAD (IDFUNCIONALIDAD,CODIGO,DESCRIPCION,PERMISO,NOMBRERECURSO,IDMODULO)
  VALUES (413, 'PROCESSEDPRODUCT', NULL, 15, 'ProcessedProduct.new', 6); 
INSERT  INTO DERECHOACCESO (IDFUNCIONALIDAD,IDROL,PERMISO,IDCOMPANIA,IDMODULO)
  VALUES (413, 50, 15, 1, 6);        
--commit
--
--select * from funcionalidad where codigo = 'REPORTPRODUCCTIONBALANCE';
    