--Khipus MRP PROD-75: Imlementar costos indirectos
--Diego H. Loza Fernandez
--Fecha de creacion: 05/12/2013

CREATE TABLE COSTOSINDIRECTOS (
   IDCOSTOSINDIRECTOS NUMBER (24,0) NOT NULL
  ,NOMBRE VARCHAR(512) NOT NULL
  ,MES NUMBER(2) NOT NULL
  ,ANIO	NUMBER(4) NOT NULL
  ,MONTOBS NUMBER(16,2) NOT NULL
  ,TIPO VARCHAR(512) NULL
  ,NO_CIA	VARCHAR2(2 BYTE) NULL
  ,COD_GRU	VARCHAR2(3 BYTE) NULL
  ,VERSION   NUMBER(24) NOT NULL
  ,IDCOMPANIA NUMBER(24) NOT  NULL
  ,CONSTRAINT pk_COSTOSINDIRECTOS PRIMARY KEY (IDCOSTOSINDIRECTOS)
);
--drop table COSTOSINDIRECTOS
ALTER TABLE COSTOSINDIRECTOS
ADD CONSTRAINT fk_INV_GRUPOS_COSTOSINDIRECTOS FOREIGN KEY (NO_CIA,COD_GRU) REFERENCES WISE.INV_GRUPOS(NO_CIA,COD_GRU);
--commit
ALTER TABLE ORDENPRODUCCION ADD (TOTALCOSTOINDIRECTO	NUMBER(16,2) null);
--
ALTER TABLE PRODUCTOPROCESADO ADD (UNIDADMEDIDATE VARCHAR(4) NULL);
ALTER TABLE PRODUCTOPROCESADO ADD (CANTIDAD NUMBER(7,2) NULL);
