--permiso para generar todos los vales
INSERT  INTO FUNCIONALIDAD (IDFUNCIONALIDAD,CODIGO,DESCRIPCION,PERMISO,NOMBRERECURSO,IDMODULO)
  VALUES (365, 'GENERATEALLVOUCHER', NULL, 15, 'ProductionPlanning.generateAllVoucher', 1); 
INSERT  INTO DERECHOACCESO (IDFUNCIONALIDAD,IDROL,PERMISO,IDCOMPANIA,IDMODULO)
  VALUES (365, 50, 15, 1, 9);     
  
--SELECT * FROM FUNCIONALIDAD
--Modificar servicios costos reprocesdos
--Diego H. Loza Fernandez
--Fecha de creacion: 08/02/2014
ALTER TABLE PRODUCTOBASE ADD (ESTADO	VARCHAR2(20 BYTE) NULL);
ALTER TABLE PRODUCTOREPROCESADO ADD (UNIDADES NUMBER(6,0) NULL, VOLUMEN NUMBER(8,2) NULL );
--COMMIT