--Fecha de creacion: 10/01/2014
INSERT  INTO FUNCIONALIDAD (IDFUNCIONALIDAD,CODIGO,DESCRIPCION,PERMISO,NOMBRERECURSO,IDMODULO)
  VALUES (362, 'GENERATEACCOUNTING', NULL, 15, 'Order.generate.accounting', 6); 
INSERT  INTO DERECHOACCESO (IDFUNCIONALIDAD,IDROL,PERMISO,IDCOMPANIA,IDMODULO)
  VALUES (362, 50, 15, 1, 6);     
