--Khipus MRP PROD-83: Implementar el re procesado de productos
--Diego H. Loza Fernandez
CREATE TABLE REPROCESADO(	
  IDREPROCESADO NUMBER(24,0), 
	UNIDADES NUMBER(6,0), 
	VOLUMEN NUMBER(8,2), 
	IDORDENPRODUCCION NUMBER(24,0), 
	IDMETAPRODUCTOPRODUCCION NUMBER(24,0), 
	IDCOMPANIA NUMBER(24,0),
  CONSTRAINT PK_REPROCESADO PRIMARY KEY(IDREPROCESADO)
);

ALTER TABLE REPROCESADO ADD CONSTRAINT FK_METAPROD_REPROC FOREIGN KEY (IDMETAPRODUCTOPRODUCCION)
	  REFERENCES METAPRODUCTOPRODUCCION (IDMETAPRODUCTOPRODUCCION) ENABLE;
 
ALTER TABLE REPROCESADO ADD CONSTRAINT FK_ORDENPRO_REPROC FOREIGN KEY (IDORDENPRODUCCION)
	  REFERENCES ORDENPRODUCCION (IDORDENPRODUCCION) ENABLE;
--DROP TABLE REPROCESADO    

CREATE TABLE PRODUCTOREPROCESADO(
  IDPRODUCTOREPROCESADO  NUMBER(24) NOT NULL
  ,CANTIDAD NUMBER(6) NULL
  ,IDREPROCESADO NUMBER(24) NULL
  ,IDMETAPRODUCTOPRODUCCION NUMBER(24) NULL
  ,IDCOMPANIA NUMBER(24) NOT  NULL
  ,CONSTRAINT PK_PRODUCTOREPROCESADO PRIMARY KEY(IDPRODUCTOREPROCESADO)
);
--drop TABLE PRODUCTOREPROCESADO
ALTER TABLE PRODUCTOREPROCESADO 
ADD CONSTRAINT FK_REPROC_PRODUCTRE 
FOREIGN KEY(IDREPROCESADO) REFERENCES REPROCESADO(IDREPROCESADO);

ALTER TABLE PRODUCTOREPROCESADO
ADD CONSTRAINT FK_METAPROD_PRODREPROC 
FOREIGN KEY(IDMETAPRODUCTOPRODUCCION) REFERENCES METAPRODUCTOPRODUCCION(IDMETAPRODUCTOPRODUCCION);
--commit
