--Khipus KHIPUS-50
--Regularizar los asientos contables del modulo de produccion
--Diego H. Loza Fernandez
--Fecha de creacion: 10/03/2014
alter table ordenproduccion add (NO_TRANS	VARCHAR2(10 BYTE) null);
alter table productosimple add (NO_TRANS	VARCHAR2(10 BYTE) null);
--commit
-- Crear permisos para la planificacion 
INSERT  INTO FUNCIONALIDAD (IDFUNCIONALIDAD,CODIGO,DESCRIPCION,PERMISO,NOMBRERECURSO,IDMODULO)
  VALUES (368, 'ADDORDERPRODUCTION', NULL, 15,'ProductionPlanning.editFormulaButton', 6); 
INSERT  INTO DERECHOACCESO (IDFUNCIONALIDAD,IDROL,PERMISO,IDCOMPANIA,IDMODULO)
  VALUES (368, 50, 15, 1, 6);     
--  
INSERT  INTO FUNCIONALIDAD (IDFUNCIONALIDAD,CODIGO,DESCRIPCION,PERMISO,NOMBRERECURSO,IDMODULO)
  VALUES (369, 'CREATEREPROCCED', NULL, 15,'ProductionPlanning.createReprocess', 6); 
INSERT  INTO DERECHOACCESO (IDFUNCIONALIDAD,IDROL,PERMISO,IDCOMPANIA,IDMODULO)
  VALUES (369, 50, 15, 1, 6);    
--  
INSERT  INTO FUNCIONALIDAD (IDFUNCIONALIDAD,CODIGO,DESCRIPCION,PERMISO,NOMBRERECURSO,IDMODULO)
  VALUES (370, 'CREATEORDERPRODUCCTION', NULL, 15,'ProductionPlanning.create.orderproduction', 6); 
INSERT  INTO DERECHOACCESO (IDFUNCIONALIDAD,IDROL,PERMISO,IDCOMPANIA,IDMODULO)
  VALUES (370, 50, 15, 1, 6);    
--  
INSERT  INTO FUNCIONALIDAD (IDFUNCIONALIDAD,CODIGO,DESCRIPCION,PERMISO,NOMBRERECURSO,IDMODULO)
  VALUES (371, 'UPDATEORDERPRODUCCTION', NULL, 15,'ProductionPlanning.innerButtonUpdate', 6); 
INSERT  INTO DERECHOACCESO (IDFUNCIONALIDAD,IDROL,PERMISO,IDCOMPANIA,IDMODULO)
  VALUES (371, 50, 15, 1, 6);    
--  
INSERT  INTO FUNCIONALIDAD (IDFUNCIONALIDAD,CODIGO,DESCRIPCION,PERMISO,NOMBRERECURSO,IDMODULO)
  VALUES (372, 'ORDERPRODUCTIONFINALIZED', NULL, 15,'ProductionPlanning.makeFinalized', 6); 
INSERT  INTO DERECHOACCESO (IDFUNCIONALIDAD,IDROL,PERMISO,IDCOMPANIA,IDMODULO)
  VALUES (372, 50, 15, 1, 6);    
--  
INSERT  INTO FUNCIONALIDAD (IDFUNCIONALIDAD,CODIGO,DESCRIPCION,PERMISO,NOMBRERECURSO,IDMODULO)
  VALUES (373, 'ORDERPRODUCTIONEXECUTED', NULL, 15,'ProductionPlanning.makeExecuted', 6); 
INSERT  INTO DERECHOACCESO (IDFUNCIONALIDAD,IDROL,PERMISO,IDCOMPANIA,IDMODULO)
  VALUES (373, 50, 15, 1, 6);    
--  
INSERT  INTO FUNCIONALIDAD (IDFUNCIONALIDAD,CODIGO,DESCRIPCION,PERMISO,NOMBRERECURSO,IDMODULO)
  VALUES (374, 'ORDERPRODUCTIONGENERATEDREPORTDETAIL', NULL, 15,'ProductionPlanning.generateSummaryDocumnt', 6); 
INSERT  INTO DERECHOACCESO (IDFUNCIONALIDAD,IDROL,PERMISO,IDCOMPANIA,IDMODULO)
  VALUES (374, 50, 15, 1, 6);    
--  
INSERT  INTO FUNCIONALIDAD (IDFUNCIONALIDAD,CODIGO,DESCRIPCION,PERMISO,NOMBRERECURSO,IDMODULO)
  VALUES (375, 'ORDERPRODUCTIONDELETE', NULL, 15,'ProductionPlanning.deleteOrderProducction', 6); 
INSERT  INTO DERECHOACCESO (IDFUNCIONALIDAD,IDROL,PERMISO,IDCOMPANIA,IDMODULO)
  VALUES (375, 50, 15, 1, 6);    
--SELECT * FROM FUNCIONALIDAD  
INSERT  INTO FUNCIONALIDAD (IDFUNCIONALIDAD,CODIGO,DESCRIPCION,PERMISO,NOMBRERECURSO,IDMODULO)
  VALUES (376, 'UPDATEORDERPRODUCTION', NULL, 15,'ProductionPlanning.materialUpdate', 6); 
INSERT  INTO DERECHOACCESO (IDFUNCIONALIDAD,IDROL,PERMISO,IDCOMPANIA,IDMODULO)
  VALUES (376, 50, 15, 1, 6);    
--  
INSERT  INTO FUNCIONALIDAD (IDFUNCIONALIDAD,CODIGO,DESCRIPCION,PERMISO,NOMBRERECURSO,IDMODULO)
  VALUES (377, 'ADDORDERPRODUCTIONMATERIAL', NULL, 15,'ProductionPlanning.addMaterial', 6); 
INSERT  INTO DERECHOACCESO (IDFUNCIONALIDAD,IDROL,PERMISO,IDCOMPANIA,IDMODULO)
  VALUES (377, 50, 15, 1, 6);      
--  
INSERT  INTO FUNCIONALIDAD (IDFUNCIONALIDAD,CODIGO,DESCRIPCION,PERMISO,NOMBRERECURSO,IDMODULO)
  VALUES (378, 'REMOVEORDERPRODUCTIONMATERIAL', NULL, 15,'ProductionPlanning.removeMaterial', 6); 
INSERT  INTO DERECHOACCESO (IDFUNCIONALIDAD,IDROL,PERMISO,IDCOMPANIA,IDMODULO)
  VALUES (378, 50, 15, 1, 6);        
--  
INSERT  INTO FUNCIONALIDAD (IDFUNCIONALIDAD,CODIGO,DESCRIPCION,PERMISO,NOMBRERECURSO,IDMODULO)
  VALUES (379, 'UPDATEINPUT', NULL, 15,'ProductionOrder.materialProduccion.modifyInputMount', 6); 
INSERT  INTO DERECHOACCESO (IDFUNCIONALIDAD,IDROL,PERMISO,IDCOMPANIA,IDMODULO)
  VALUES (379, 50, 15, 1, 6);        
--  
INSERT  INTO FUNCIONALIDAD (IDFUNCIONALIDAD,CODIGO,DESCRIPCION,PERMISO,NOMBRERECURSO,IDMODULO)
  VALUES (380, 'UPDATEMATERIAL', NULL, 15,'ProductionOrder.materialProduccion.setMountUsed', 6); 
INSERT  INTO DERECHOACCESO (IDFUNCIONALIDAD,IDROL,PERMISO,IDCOMPANIA,IDMODULO)
  VALUES (380, 50, 15, 1, 6);          
--  
INSERT  INTO FUNCIONALIDAD (IDFUNCIONALIDAD,CODIGO,DESCRIPCION,PERMISO,NOMBRERECURSO,IDMODULO)
  VALUES (381, 'ENTERPRODUCTTOEWAREHOUSE', NULL, 15,'ProductionPlanning.generateValeOrder', 6); 
INSERT  INTO DERECHOACCESO (IDFUNCIONALIDAD,IDROL,PERMISO,IDCOMPANIA,IDMODULO)
  VALUES (381, 50, 15, 1, 6);              
--  
INSERT  INTO FUNCIONALIDAD (IDFUNCIONALIDAD,CODIGO,DESCRIPCION,PERMISO,NOMBRERECURSO,IDMODULO)
  VALUES (382, 'ADDPRODUCTTOBASEPRODUCT', NULL, 15,'ProductoPlanning.message.addProductToBaseProduct', 6); 
INSERT  INTO DERECHOACCESO (IDFUNCIONALIDAD,IDROL,PERMISO,IDCOMPANIA,IDMODULO)
  VALUES (382, 50, 15, 1, 6);            
--  
INSERT  INTO FUNCIONALIDAD (IDFUNCIONALIDAD,CODIGO,DESCRIPCION,PERMISO,NOMBRERECURSO,IDMODULO)
  VALUES (383, 'SAVEREPROCCED', NULL, 15,'ProductoPlanning.message.saveReprocced', 6); 
INSERT  INTO DERECHOACCESO (IDFUNCIONALIDAD,IDROL,PERMISO,IDCOMPANIA,IDMODULO)
  VALUES (383, 50, 15, 1, 6);            
--  
INSERT  INTO FUNCIONALIDAD (IDFUNCIONALIDAD,CODIGO,DESCRIPCION,PERMISO,NOMBRERECURSO,IDMODULO)
  VALUES (384, 'DELETEREPROCCED', NULL, 15,'ProductoPlanning.message.deleteReprocced', 6); 
INSERT  INTO DERECHOACCESO (IDFUNCIONALIDAD,IDROL,PERMISO,IDCOMPANIA,IDMODULO)
  VALUES (384, 50, 15, 1, 6);              
--select * from funcionalidad    
--SELECT * FROM MODULO
--COMMIT