--Khipus MRP PROD-87: Implementar el cierre y aprovación de periodo(quincena) para produccion
--Diego H. Loza Fernandez
--Fecha de creacion: 10/04/2014
--ALTER TABLE PLANILLAACOPIO ADD (ESTATO VARCHAR(10) default 'PENDING'); ya cuenta con un estado
ALTER TABLE SESIONACOPIO ADD (ESTADO VARCHAR(10) default 'PENDING');
ALTER TABLE NOTARECHAZOMATERIAPRIMA ADD (ESTADO VARCHAR(10) default 'PENDING');
ALTER TABLE MOVIMIENTOSALARIOPRODUCTOR ADD (ESTADO VARCHAR(10) default 'PENDING');
ALTER TABLE MOVIMIENTOSALARIOGAB ADD (ESTADO VARCHAR(10) default 'PENDING');
ALTER TABLE PLANILLAPAGOMATERIAPRIMA ADD (ESTADO VARCHAR(10) default 'PENDING');
--

CREATE TABLE LOGZONAPRODUCTIVA(
   IDLOGZONAPRODUCTIVA NUMBER(24,0) NOT NULL
  ,FECHA DATE
  ,ESTADO VARCHAR(10)
  ,IDPRODUCTORMATERIAPRIMA NUMBER(24,0) NOT NULL
  ,IDZONAPRODUCTIVA NUMBER(24,0) NOT NULL
  ,IDCOMPANIA varchar2(2 char) NOT NULL 
  ,CONSTRAINT PK_LOGZONAPRODUCTIVA PRIMARY KEY(IDLOGZONAPRODUCTIVA)
);
--DROP TABLE LOGZONAPRODUCTIVA
ALTER TABLE LOGZONAPRODUCTIVA ADD CONSTRAINT FK_LOGZONAPROD_PRODMATPRIM FOREIGN KEY (IDPRODUCTORMATERIAPRIMA)
REFERENCES PRODUCTORMATERIAPRIMA(IDPRODUCTORMATERIAPRIMA);
ALTER TABLE LOGZONAPRODUCTIVA ADD CONSTRAINT FK_LOGZONAPROD_ZONAPROD FOREIGN KEY (IDZONAPRODUCTIVA)
REFERENCES ZONAPRODUCTIVA(IDZONAPRODUCTIVA);
--COMMIT

--commit

