--SELECT * FROM FUNCIONALIDAD
--Modificar servicios costos reprocesdos
--Diego H. Loza Fernandez
alter table PRODUCTOSIMPLE add (
   COSTOTOTALMANOOBRA	NUMBER(16,6) NULL  
  ,COSTOTOTALINDIRECTO	NUMBER(16,6) NULL  
  ,COSTOUNITARIO	NUMBER(16,6) NULL  
  ,PORCENTAJEGRASA	NUMBER(16,6) NULL  
  ,COSTOTOTALPRODUCCION	NUMBER(16,6) NULL  
  ); 
  
ALTER TABLE COSTOSINDIRECTOS ADD(IDPRODUCTOSIMPLE NUMBER(16,6) NULL);

ALTER TABLE COSTOSINDIRECTOS ADD CONSTRAINT FK_SIMPLE_COSTSINFIRECTOS FOREIGN KEY (IDPRODUCTOSIMPLE) 
REFERENCES PRODUCTOSIMPLE(IDPRODUCTOSIMPLE);

CREATE TABLE PRODUCTOSIMPLEPROCESADO(
  IDPRODUCTOSIMPLEPROCESADO NUMBER(16,6) NOT NULL
  ,IDPRODUCTOSIMPLE NUMBER(24,0) NOT NULL
  ,IDMETAPRODUCTOPRODUCCION NUMBER(24,0) NOT NULL  
  ,CONSTRAINT PK_PRODUCTOSIMPLEPROCESADO PRIMARY KEY(IDPRODUCTOSIMPLEPROCESADO)
);
ALTER TABLE PRODUCTOSIMPLEPROCESADO ADD CONSTRAINT FK_PRODSIMPROC_PRODSIMPL FOREIGN KEY (IDPRODUCTOSIMPLE)
REFERENCES PRODUCTOSIMPLE(IDPRODUCTOSIMPLE);
ALTER TABLE  PRODUCTOSIMPLEPROCESADO ADD CONSTRAINT FK_PRODSIMPROC_METAPROD FOREIGN KEY (IDMETAPRODUCTOPRODUCCION)
REFERENCES METAPRODUCTOPRODUCCION (IDMETAPRODUCTOPRODUCCION);
--commit
--alter table PRODUCTOSIMPLEPROCESADO drop constraint FK_PRODSIMPROC_PRODSIMPL
