--Khipus MRP PROD-73: Aumentar el listado de horas trabajadas al reporte general de produccion.
--Diego H. Loza Fernandez
--Fecha de creacion: 25/11/2013

ALTER TABLE tarjetatiempoempleado ADD (COSTOPORHORA	number(16,2) null);
--commit;
--Khipus MRP PROD-74: Modificar el registro de horas de la mano de obra
--Diego H. Loza Fernandez
--Fecha de creacion: 26/11/2013

ALTER TABLE TIPOTAREAPROD ADD (NO_CIA	VARCHAR2(2 BYTE) NOT NULL);
ALTER TABLE TIPOTAREAPROD ADD (COD_GRU	VARCHAR2(3 BYTE) NOT NULL);

ALTER TABLE TIPOTAREAPROD
ADD CONSTRAINT fk_INV_GRUPOS_TIPOTAREAPROD FOREIGN KEY (NO_CIA,COD_GRU) REFERENCES WISE.INV_GRUPOS(NO_CIA,COD_GRU);

CREATE TABLE CONFIGRUPO (
   IDCONFIGRUPO NUMBER (24,0) NOT NULL
  ,TIPO VARCHAR(255) NULL
  ,NO_CIA	VARCHAR2(2 BYTE) NOT NULL
  ,COD_GRU	VARCHAR2(3 BYTE) NOT NULL
  ,CONSTRAINT pk_CONFIGRUPO PRIMARY KEY (IDCONFIGRUPO)
);

ALTER TABLE CONFIGRUPO
ADD CONSTRAINT fk_INV_GRUPOS_CONFIGRUPO FOREIGN KEY (NO_CIA,COD_GRU) REFERENCES WISE.INV_GRUPOS(NO_CIA,COD_GRU);

INSERT INTO CONFIGRUPO ( IDCONFIGRUPO,TIPO,NO_CIA,COD_GRU) VALUES (1,'AREA_PRODUCTOS','01','6');
--commit