--Khipus MRP PROD-34: Diego Loza
--Crear la tabla

Create table TIPOMOVIMIENTOPRODUCTOR (
	IDTIPOMOVIMIENTOPRODUCTOR NUMBER(24,0) NOT NULL ,
	NOMBRE VARCHAR(255) NOT NULL,	
	MONEDA VARCHAR(10),
  TIPOMOVIMIENTO VARCHAR(20),	
  IDCOMPANIA NUMBER(24,0) NOT NULL ,
 CONSTRAINT pk_TIPOMOVIMIENTOPRODUCTOR primary key (IDTIPOMOVIMIENTOPRODUCTOR) 
);
--drop table tipomovimientoproductor
--drop table TIPOMOVIMIENTOPRODUCTOR
Create table TIPOMOVIMIENTOGAB (
	IDTIPOMOVIMIENTOGAB NUMBER(24,0) NOT NULL ,
	NOMBRE VARCHAR(255) NOT NULL,	
	MONEDA VARCHAR(10),	
	TIPOMOVIMIENTO VARCHAR(20) NOT NULL,
  IDCOMPANIA NUMBER(24,0) NOT NULL ,
 CONSTRAINT pk_TIPOMOVIMIENTOGAB primary key (IDTIPOMOVIMIENTOGAB) 
);
--commit
-- drop table MOVIMIENTOSALARIOPRODUCTOR 
Create table MOVIMIENTOSALARIOGAB (
  IDMOVIMIENTOSALARIOGAB NUMBER(24,0) NOT NULL ,
	IDZONAPRODUCTIVA NUMBER(24,0) NOT NULL ,
	DESCRIPCION varchar(255),
  FECHA DATE NOT NULL,
  VALOR NUMBER(16,2) DEFAULT 0.0,
	IDTIPOMOVIMIENTOGAB NUMBER(24,0) NOT NULL ,
  IDCOMPANIA NUMBER(24,0) NOT NULL ,
 CONSTRAINT pk_MOVIMIENTOSALARIOGAB primary key (IDMOVIMIENTOSALARIOGAB) 
);
-- DROP TABLE MOVIMIENTOSALARIOGAB
ALTER TABLE MOVIMIENTOSALARIOGAB
ADD CONSTRAINT fk_ZONAPRODUCTIVA FOREIGN KEY (IDZONAPRODUCTIVA) REFERENCES ZONAPRODUCTIVA(IDZONAPRODUCTIVA);

ALTER TABLE MOVIMIENTOSALARIOGAB
ADD CONSTRAINT fk_TIPOMOVIMIENTOGAB FOREIGN KEY (IDTIPOMOVIMIENTOGAB) REFERENCES TIPOMOVIMIENTOGAB(IDTIPOMOVIMIENTOGAB);
--commit
Create table MOVIMIENTOSALARIOPRODUCTOR (
  IDMOVIMIENTOSALARIOPRODUCTOR NUMBER(24,0) NOT NULL ,
	IDPRODUCTORMATERIAPRIMA NUMBER(24,0) NOT NULL ,  
	DESCRIPCION varchar(255),
  VALOR NUMBER(16,2) DEFAULT 0.0,
  FECHA DATE NOT NULL,
  IDTIPOMOVIMIENTOPRODUCTOR NUMBER(24,0) NOT NULL ,
  IDCOMPANIA NUMBER(24,0) NOT NULL ,
  CONSTRAINT pk_MOVIMIENTOSALARIOPRODUCTOR primary key (IDMOVIMIENTOSALARIOPRODUCTOR) 
);
--drop table MOVIMIENTOSALARIOPRODUCTOR
--delete MOVIMIENTOSALARIOPRODUCTOR
ALTER TABLE MOVIMIENTOSALARIOPRODUCTOR
ADD CONSTRAINT fk_PRODUCTORMATERIAPRIMA FOREIGN KEY (IDPRODUCTORMATERIAPRIMA) REFERENCES PRODUCTORMATERIAPRIMA(IDPRODUCTORMATERIAPRIMA);

ALTER TABLE MOVIMIENTOSALARIOPRODUCTOR
ADD CONSTRAINT fk_TIPOMOVIMIENTOPRODUCTOR FOREIGN KEY (IDTIPOMOVIMIENTOPRODUCTOR) REFERENCES TIPOMOVIMIENTOPRODUCTOR(IDTIPOMOVIMIENTOPRODUCTOR);
--commit
---------
